### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/tinytable#1]
+ [ ] caption
    - [ ] HTML: https://getbootstrap.com/docs/4.0/content/tables/#captions
+ [x] logo
+ [ ] `digits` argument
+ [ ] scale up/down
+ [x] `vlines` and `hlines` argument in `tt()`
+ [x] `hlines` commented out in `tt()` because broken
+ [ ] width of the whole table: tabularray allows other widths with `X[]`, the default is `\textwidth`
+ [ ] span
    + [ ] `group_row(x, i, list(a = 2:3, b = 4:7))` --- find position by line numbers in the body block
    + [ ] `group_column()` --- harder to pick columns because the LaTeX is built already
+ [ ] Footnotes
+ [ ] Remarks
+ [ ] Images
    + [ ] local
    + [ ] web
    + [ ] inline plots
+ [ ]  `output` formats
    + [ ] Typst
    + [ ] Bootstrap tables
        + [ ] bootstrap_class = NULL to produce raw HTML table.
        + [ ] ids for different rows so users can target with CSS
        + [ ] fontVariant vs fontFamily
    + [x] Markdown tables
    + [ ] `longtblr`
    + [ ] valid file path. Guess by extension.
+ [ ] Rmarkdown and Quarto
    - [ ] fig.cap and code chunk label.
    - [x] auto detect output format
+ [x] Should we be opinionated and *not* supply these in the `tt()` function?
    + [x] align in `tt()`: I may want to be opinionated and say that left align is default.
    + [x] placement

# table environment

From a `kableExtra` issue:

> A direct issue is that code that compiles well with knitr does not with Quarto.
With Quarto, the argument caption of kable is not used (it actually produces invalid LaTeX). The table caption is in the code chunk option #| tbl-cap: and is added after \begin{table}.
Since kable_styling(full_width = TRUE) does not produce a "table" environment, the caption of the table is just not inserted into the LaTeX output.

> I suggest to have a consistent behavior of kable_styling() that should not add a table environment by default but allow it with an argument or more simply document that kable(..., table.envir = "table") does it if necessary.
This code chunk produces a correct full-width table in Quarto

The only counter brought up for not including a `table` environment every time is the use of `longtable`
